server:
  port: 4005

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-service-route
              uri: http://patient-service:4000
              predicates:
                - Path=/patients/**
            - id: api-docs-patient-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api-docs/patients
              filters:
                - RewritePath=/api-docs/patients,/v3/api-docs
