spring.application.name=patient-service

spring.config.import=optional:file:.env[.properties]

spring.h2.console.path=/h2-console
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.h2.Driver


spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

server.port=4000

logging.level.root=info