POST http://localhost:4000/patients
Content-Type: application/json

{
  "adress": "789 Willow St, Springfield",
  "dateofBirth": "1987-10-17",
  "id": "223e4567-e89b-12d3-a456-426614174014",
  "mail": "isabella@example.com",
  "name": "Isabella Walker",
  "registeredDate": "2024-03-29"
}

